version: '3.7'
services:
  confluent-zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    container_name: confluent-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: "1"
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ./confluent-zookeeper/data:/var/lib/zookeeper/data
      - ./confluent-zookeeper/log:/var/lib/zookeeper/log
    network_mode: "host"
  confluent-kafka:
    image: confluentinc/cp-kafka:5.0.0
    container_name: confluent-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_BROKER_ID: "1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - ./confluent-kafka/data:/var/lib/kafka/data
    depends_on:
      - confluent-zookeeper
    network_mode: "host"
  confluent-schema-registry:
    image: confluentinc/cp-schema-registry:5.0.0
    container_name: confluent-schema-registry
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://localhost:9092
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: localhost:2181
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: http://localhost:8081
      SCHEMA_REGISTRY_DEBUG: "true"
    ports:
      - "8081:8081"
    depends_on:
      - confluent-zookeeper
      - confluent-kafka
    network_mode: "host"
  confluent-rest-proxy:
    image: confluentinc/cp-kafka-rest:5.0.0
    container_name: confluent-rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: localhost
      KAFKA_REST_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_REST_LISTENERS: http://localhost:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://localhost:8081
    depends_on:
      - confluent-zookeeper
      - confluent-kafka
      - confluent-schema-registry
    network_mode: "host"
  confluent-kafka-connect:
    image: confluentinc/cp-kafka-connect:5.0.0
    container_name: confluent-kafka-connect
    environment:
      CONNECT_BOOTSTRAP_SERVERS: localhost:9092
      CONNECT_REST_PORT: 8082
      CONNECT_GROUP_ID: "quickstart"
      CONNECT_CONFIG_STORAGE_TOPIC: "quickstart-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "quickstart-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "quickstart-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_PLUGIN_PATH: "/usr/share/java"
    network_mode: "host"